"""Canonical reward and answer-verification interfaces."""

from .audit import (
    AuditCorpusError,
    AuditFailure,
    AuditProvenance,
    AuditProvenanceError,
    LoadedAuditCorpus,
    VerifierAuditCase,
    VerifierAuditReport,
    collect_audit_provenance,
    load_audit_corpus,
    run_verifier_audit,
    write_audit_report,
)
from .verifier import (
    DEFAULT_VERIFIER_POLICY,
    AnswerSource,
    ExactMathVerifier,
    ExtractionResult,
    ExtractionStatus,
    ParsedAnswer,
    ParseStatus,
    RewardBatch,
    VerificationResult,
    VerificationStatus,
    VerifierInfrastructureError,
    VerifierPolicy,
    exact_math_reward,
    extract_prediction_answer,
    extract_reference_answer,
    verifier_backend_versions,
    verify_math_answer,
)

__all__ = [
    "DEFAULT_VERIFIER_POLICY",
    "AnswerSource",
    "AuditCorpusError",
    "AuditFailure",
    "AuditProvenance",
    "AuditProvenanceError",
    "ExactMathVerifier",
    "ExtractionResult",
    "ExtractionStatus",
    "LoadedAuditCorpus",
    "ParseStatus",
    "ParsedAnswer",
    "RewardBatch",
    "VerificationResult",
    "VerificationStatus",
    "VerifierAuditCase",
    "VerifierAuditReport",
    "VerifierInfrastructureError",
    "VerifierPolicy",
    "collect_audit_provenance",
    "exact_math_reward",
    "extract_prediction_answer",
    "extract_reference_answer",
    "load_audit_corpus",
    "run_verifier_audit",
    "verifier_backend_versions",
    "verify_math_answer",
    "write_audit_report",
]
